# Generated by Django 6.0.2 on 2026-03-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
