# Generated by Django 6.0.2 on 2026-03-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_registrationrequest_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_limit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_used_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_ai_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
